#!/bin/bash

set -e

./scripts/bundle
./scripts/test

echo "Copying binaries"

chmod +x dist/git-interactive
cp dist/git-interactive ~/.bin/
cp dist/git-interactive ~/dev/workspace/castle-builder-artefacts/
